#!/bin/bash

filename='./doofile'

containerName=""
start=""

while read -r line  || [ -n "$line" ]; do
    IFS=':' read -r -a data <<< "$line"
    if [[ "${data[0]}" == "container-name" ]]
    then
    containerName=${data[1]}
    fi

    if [[ "${data[0]}" == "start" ]]
    then
    start="$(IFS=':'; printf '%s' "${data[*]:1}")"
    echo start
    fi
done < $filename

if [[ "$1" == "start" ]]
    then
    echo "??"
    echo "$start"
    $start
elif [[ ! "$containerName" == "" ]]
then
    containerID=$(docker ps -aqf "name=$containerName")
    docker exec -it $containerID "$@"
else
echo "[!] found no container configuration doofile"
fi
